### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by SuperNici** [7USTIN/manga-cli#1]
Hey @7USTIN, i made a PKGBUILD for this project. Feel free to check it out before I submit it to the AUR

```
# Maintainer: Nici <NiciTheNici at protonmail dot com>
pkgname='manga-cli-git'
_pkgname='manga-cli'
pkgver=r4.99c46ee
pkgrel=1
pkgdesc="A Bash script for reading mangas via the terminal by scraping Mangakakalot."
arch=('any')
url="https://github.com/7USTIN/manga-cli"
license=('GPL3')
depends=('coreutils' 'curl' 'sed' 'awk' 'diffutils' 'patch' 'imagemagick' 'zathura' 'zathura-pdf-mupdf')
makedepends=('git') # 'bzr', 'git', 'mercurial' or 'subversion'
source=('git+https://github.com/7USTIN/manga-cli.git')
md5sums=('SKIP')

pkgver() {
	cd "$srcdir/${_pkgname}"
	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

package() {
	cd "$srcdir/$_pkgname"
	install -Dm755 ./manga-cli "$pkgdir/usr/bin/manga-cli"
}

```
It installed correctly on my end.

**Comment by 7USTIN** [comment]
Thank you, @SuperNici. I really appreciate it!
LGTM!

**Comment by SuperNici** [comment]
Urban dictionary sucks ass lmao
![photo_2022-02-06_22-09-00](https://user-images.githubusercontent.com/51826257/152701424-1ce414ae-7845-40cf-8748-991163cb5949.jpg)

Its on the AUR now though! Do `paru -S manga-cli-git` to install it. It _**should**_ automatically get updated whenever you make a new commit, so keep that in mind!

Might add this to the readme, but I'm too tired today. Thanks for the project btw! Its great and i look forward to contributing to it in the future!
